version: '3.5'
services:
  application:
    build: .
    container_name: "DCservice" 
    ports: 
      - "8080:8080"
    environment:
    - Redis=redis:6379
    restart: always 
  
  redis:
    image: "redis"
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"